In [103]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

df = pd.read_csv(r'C:\Users\Sanket M\OneDrive\Documents\SymptomSolver\dataset.csv')
print(df)

                                      Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischrom

In [104]:
df['Symptom_5'].unique()

array([nan, ' cough', ' chest_pain', ' loss_of_appetite',
       ' abdominal_pain', ' spotting_ urination', ' internal_itching',
       ' passage_of_gases', ' irregular_sugar_level',
       ' blurred_and_distorted_vision', ' family_history',
       ' mucoid_sputum', ' lack_of_concentration', ' excessive_hunger',
       ' stiff_neck', ' loss_of_balance', ' high_fever',
       ' yellowish_skin', ' headache', ' nausea', ' fatigue',
       ' dark_urine', ' yellowing_of_eyes', ' distention_of_abdomen',
       ' history_of_alcohol_consumption', ' breathlessness', ' sweating',
       ' irritation_in_anus', ' swollen_legs', ' swollen_blood_vessels',
       ' lethargy', ' dizziness', ' diarrhoea', ' swelling_joints',
       ' painful_walking', ' unsteadiness', ' small_dents_in_nails',
       ' inflammatory_nails', ' yellow_crust_ooze'], dtype=object)

In [105]:
df.tail(25)

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
4895,Chicken pox,itching,skin_rash,fatigue,lethargy,high_fever,headache,loss_of_appetite,mild_fever,swelled_lymph_nodes,malaise,red_spots_over_body,NaN,NaN,NaN,NaN,NaN,NaN
4896,Dengue,skin_rash,chills,joint_pain,vomiting,fatigue,high_fever,headache,nausea,loss_of_appetite,pain_behind_the_eyes,back_pain,malaise,muscle_pain,red_spots_over_body,NaN,NaN,NaN
4897,Typhoid,chills,vomiting,fatigue,high_fever,headache,nausea,constipation,abdominal_pain,diarrhoea,toxic_look_(typhos),belly_pain,NaN,NaN,NaN,NaN,NaN,NaN
4898,hepatitis A,joint_pain,vomiting,yellowish_skin,dark_urine,nausea,loss_of_appetite,abdominal_pain,diarrhoea,mild_fever,yellowing_of_eyes,muscle_pain,NaN,NaN,NaN,NaN,NaN,NaN
4899,Hepatitis B,itching,fatigue,lethargy,yellowish_skin,dark_urine,loss_of_appetite,abdominal_pain,yellow_urine,yellowing_of_eyes,malaise,receiving_blood_transfusion,receiving_unsterile_injections,NaN,NaN,NaN,NaN,NaN
4900,Hepatitis C,fatigue,yellowish_skin,nausea,loss_of_appetite,yellowing_of_eyes,family_history,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4901,Hepatitis D,joint_pain,vomiting,fatigue,yellowish_skin,dark_urine,nausea,loss_of_appetite,abdominal_pain,yellowing_of_eyes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4902,Hepatitis E,joint_pain,vomiting,fatigue,high_fever,yellowish_skin,dark_urine,nausea,loss_of_appetite,abdominal_pain,yellowing_of_eyes,acute_liver_failure,coma,stomach_bleeding,NaN,NaN,NaN,NaN
4903,Alcoholic hepatitis,vomiting,yellowish_skin,abdominal_pain,swelling_of_stomach,distention_of_abdomen,history_of_alcohol_consumption,fluid_overload,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4904,Tuberculosis,chills,vomiting,fatigue,weight_loss,cough,high_fever,breathlessness,sweating,loss_of_appetite,mild_fever,yellowing_of_eyes,swelled_lymph_nodes,malaise,phlegm,chest_pain,blood_in_sputum,NaN


In [106]:
df['Symptom_5'].unique()

array([nan, ' cough', ' chest_pain', ' loss_of_appetite',
       ' abdominal_pain', ' spotting_ urination', ' internal_itching',
       ' passage_of_gases', ' irregular_sugar_level',
       ' blurred_and_distorted_vision', ' family_history',
       ' mucoid_sputum', ' lack_of_concentration', ' excessive_hunger',
       ' stiff_neck', ' loss_of_balance', ' high_fever',
       ' yellowish_skin', ' headache', ' nausea', ' fatigue',
       ' dark_urine', ' yellowing_of_eyes', ' distention_of_abdomen',
       ' history_of_alcohol_consumption', ' breathlessness', ' sweating',
       ' irritation_in_anus', ' swollen_legs', ' swollen_blood_vessels',
       ' lethargy', ' dizziness', ' diarrhoea', ' swelling_joints',
       ' painful_walking', ' unsteadiness', ' small_dents_in_nails',
       ' inflammatory_nails', ' yellow_crust_ooze'], dtype=object)

In [107]:
df.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [108]:
df.drop(columns=['Symptom_7','Symptom_8','Symptom_9','Symptom_10','Symptom_11','Symptom_12','Symptom_13','Symptom_14','Symptom_15','Symptom_16','Symptom_17'], inplace=True)
df.head(5)

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN


In [109]:
dict = {"Symptom_1":"s1", "Symptom_2":"s2", "Symptom_3":"s3", "Symptom_4":"s4","Symptom_5":"s5", "Symptom_6":"s6"}
df.rename(columns=dict, inplace= True)

In [110]:
df.tail(5)

,Disease,s1,s2,s3,s4,s5,s6
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN


In [111]:
df.fillna('No Symptoms',inplace=True)

In [112]:
df.isna().sum()

Disease    0
s1         0
s2         0
s3         0
s4         0
s5         0
s6         0
dtype: int64

In [113]:
le = LabelEncoder()

df['Disease'] = le.fit_transform(df['Disease'])
df.tail(20)

,Disease,s1,s2,s3,s4,s5,s6
4900,20,fatigue,yellowish_skin,nausea,loss_of_appetite,yellowing_of_eyes,family_history
4901,21,joint_pain,vomiting,fatigue,yellowish_skin,dark_urine,nausea
4902,22,joint_pain,vomiting,fatigue,high_fever,yellowish_skin,dark_urine
4903,3,vomiting,yellowish_skin,abdominal_pain,swelling_of_stomach,distention_of_abdomen,history_of_alcohol_consumption
4904,36,chills,vomiting,fatigue,weight_loss,cough,high_fever
4905,10,continuous_sneezing,chills,fatigue,cough,high_fever,headache
4906,34,chills,fatigue,cough,high_fever,breathlessness,sweating
4907,13,constipation,pain_during_bowel_movements,pain_in_anal_region,bloody_stool,irritation_in_anus,No Symptoms
4908,18,vomiting,breathlessness,sweating,chest_pain,No Symptoms,No Symptoms
4909,39,fatigue,cramps,bruising,obesity,swollen_legs,swollen_blood_vessels


In [114]:
df['s2'].unique()

array([' skin_rash', ' nodal_skin_eruptions', ' shivering', ' chills',
       ' acidity', ' ulcers_on_tongue', ' vomiting', ' yellowish_skin',
       ' stomach_pain', ' loss_of_appetite', ' indigestion',
       ' patches_in_throat', ' high_fever', ' weight_loss',
       ' restlessness', ' sunken_eyes', ' dehydration', ' cough',
       ' chest_pain', ' dizziness', ' headache', ' weakness_in_limbs',
       ' neck_pain', ' weakness_of_one_body_side', ' fatigue',
       ' joint_pain', ' lethargy', ' nausea', ' abdominal_pain',
       ' pain_during_bowel_movements', ' pain_in_anal_region',
       ' breathlessness', ' sweating', ' cramps', ' bruising',
       ' weight_gain', ' cold_hands_and_feets', ' mood_swings',
       ' anxiety', ' knee_pain', ' stiff_neck', ' swelling_joints',
       ' pus_filled_pimples', ' blackheads', ' bladder_discomfort',
       ' foul_smell_of urine', ' skin_peeling', ' blister'], dtype=object)

In [115]:
df['s1'] = le.fit_transform(df['s1'])
df['s2'] = le.fit_transform(df['s2'])
df['s3'] = le.fit_transform(df['s3'])
df['s4'] = le.fit_transform(df['s4'])
df['s5'] = le.fit_transform(df['s5'])
df['s6'] = le.fit_transform(df['s6'])
df.head(20)

,Disease,s1,s2,s3,s4,s5,s6
0,15,33,35,35,11,38,32
1,15,24,27,18,50,38,32
2,15,33,27,18,50,38,32
3,15,33,35,18,50,38,32
4,15,33,35,35,50,38,32
5,15,24,27,18,50,38,32
6,15,33,27,18,50,38,32
7,15,33,35,18,50,38,32
8,15,33,35,35,50,38,32
9,15,33,35,35,11,38,32


In [116]:
df['s5'].unique()

array([38,  4,  3, 21,  0, 28, 16, 26, 17,  1, 10, 23, 19,  9, 29, 22, 13,
       37, 12, 24, 11,  5, 36,  7, 14,  2, 30, 18, 33, 32, 20,  8,  6, 31,
       25, 34, 27, 15, 35])

In [117]:
# Splitting  Dataset in two parts

X = df[['s1','s2','s3','s4','s5','s6']]   # Feature
y = df['Disease']    # Target Column

In [118]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)          # test size 20% 


dt_model = DecisionTreeClassifier()
dt_model.fit(X_train,y_train)


DecisionTreeClassifier()

In [119]:
y_pred = dt_model.predict(X_test)
print(y_pred)

[ 2  2 24  1  9 23 25  5 19 30 38 12 21 35  3  3 13 22 12  7  6 40 19  6
  4 20 34 30 26 30  9 19 17 21 39 30 28 14 34 38 20  0 23 12 28 17 25 19
 35 35 18 36 39  4 24 20 37 10 38 33 25 24 36 18  0 26 32  1  0 13 15  6
  2 22 26  9 27 27 10 30 16 27 16 14 19  1 28 17  0 11 26 29 21  3 36 17
 29 18 34 11 23  6  3  4 33 39 16 30 22  1 21 39 18 25 12 14 26 28 25  3
  7 35 32  8  5 34 17 24 35 31 11  7  7  7  9  2 19 34 13 37 33 18 35 19
 21 31 14 39 36  3 12 31 33 37 23 37 25 21  3  4  6 28  1 18 40 37 29  6
 27 24 40 21 40 17 34 27  1 40 10  8 29  1  4 40 30 37 12 19 11 38 37  2
 39 34 22  8 15  7 19 31 17 40 39 11 15  0 16  4  9  8 19 31 18 13 17 28
 29 18  9 21 11  3  3 23 32 40  8 17 26 35  5 13 37 34 35 14 31  6 12  5
 10 20  4 39 32 36 36  9 32 18 19 22 13 11 27 34 13 10 10  1 18 10 10 14
  0 26 10  8 13 25 26  5 29 37 26 16 30 27 34  1 37 24 40 35 24 33  6 36
 12 33 16 11 22 40 15 11 19 14  1 15 36  6 27 22 35 19 23 31 16 32 20 15
 33  1 25  7  6 20 13 15 40 22 30 16 38 30 23  1  6

In [120]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9979674796747967


In [121]:
print(confusion_matrix(y_test,y_pred))

[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


In [122]:
# import pickle

import pickle

with open('d_model.pkl', 'wb') as f:
    pickle.dump(dt_model, f)

# Save the model using pickle
with open(r'C:\Users\Sanket M\OneDrive\Documents\SymptomSolver\d_model.pkl', 'wb') as model_file:
    pickle.dump(dt_model, model_file)